" ================== gui/gvim-options:
"
execute pathogen#infect()
"
"============================= Gui-Window-Position,Size,... (somme only for MsWin):
"_ set  guifont=Consolas:h10
set guifont=Source\ Code\ Pro\ 9     " HP13 + Lv13-ok-by-xfce4_appearance_no_custom_dpi, i.e. just 100%
set lines=50 columns=160 "window-size
"
"====== behaves/menus/... of gui: ===============================
behave xterm  " /OR: mswin	" mouse behaving like unix xterms OR mswin ; !!changes other guioptions too, so the sequence IS relevant !!
set guioptions-=T	" no toolbar/icons. otherwise see 'toolbar' or gui-toolbar
set guioptions+=b	" Bottom horizontal scrollbar is present
set guioptions+=a   " !!!vim becomes the owner of copy/paste buffer with mouse : so in WIN like in xterm, if behave xterm
set guioptions+=g   " Grey menu items: Make menu items that are not active grey.
set guioptions+=R	" Right-hand scrollbar is present when there is a vertically split window.
set guioptions+=i	" Use a Vim icon

"====== tab-pages/windows:
set guitablabel=%t	" only fileName, withouth path, shown in tab-lables
let &titlestring='GV: ' . statuslinestr  "ONLY to see if it is a console-vim or GVim-window.

"====== mouse/... of gui: ===============================
" --!!-if mouse/ttymouse disabled, then all other mouse/behave/mouseMappings-options have NO effects! so with mouse= all other mouse-settings here are ignored!
set mouse=     "disabling mouse in gvim : BUT then problem inmswin: rightclick extends the selction as default!
" set mousemodel=popup  
" again here/doppel if middle-mouse-click always work??:
" middle-mouse-click-paste_Lx in mswin:  middle-mouse-signal on mswins mapped to insert-paste as in Lx in both normal+insert-modes :
nnoremap  <C-S-F22>    i<c-r>+
inoremap  <C-S-F22>    <c-r>+
" ------
"
"====== re-dones/... to get sure...:
set fileformat=unix
